import Foundation

public struct SensitiveFilter: Sendable {
    public static let knownPasswordManagerBundleIds: Set<String> = [
        "com.agilebits.onepassword7",
        "com.agilebits.onepassword-osx",
        "com.1password.1password",
        "com.bitwarden.desktop",
        "com.lastpass.LastPass",
        "com.dashlane.dashlanephonefinal",
    ]

    public static let sensitivePasteboardTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    public init() {}

    public func shouldSkip(_ raw: RawPasteboardContent) -> Bool {
        for type in raw.types where Self.sensitivePasteboardTypes.contains(type) {
            return true
        }
        if let app = raw.frontmostAppBundleId,
           Self.knownPasswordManagerBundleIds.contains(app) {
            return true
        }
        return false
    }
}
