import XCTest
@testable import myPasteCore

final class SensitiveFilterTests: XCTestCase {
    func test_concealedType_isSkipped() {
        let raw = RawPasteboardContent(
            types: ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"],
            string: "secret", imageData: nil, frontmostAppBundleId: "com.apple.Safari")
        XCTAssertTrue(SensitiveFilter().shouldSkip(raw))
    }

    func test_autoGeneratedType_isSkipped() {
        let raw = RawPasteboardContent(
            types: ["org.nspasteboard.AutoGeneratedType"],
            string: "x", imageData: nil, frontmostAppBundleId: nil)
        XCTAssertTrue(SensitiveFilter().shouldSkip(raw))
    }

    func test_1password_bundleId_isSkipped() {
        let raw = RawPasteboardContent(
            types: ["public.utf8-plain-text"], string: "pw",
            imageData: nil, frontmostAppBundleId: "com.1password.1password")
        XCTAssertTrue(SensitiveFilter().shouldSkip(raw))
    }

    func test_bitwarden_isSkipped() {
        let raw = RawPasteboardContent(
            types: ["public.utf8-plain-text"], string: "pw",
            imageData: nil, frontmostAppBundleId: "com.bitwarden.desktop")
        XCTAssertTrue(SensitiveFilter().shouldSkip(raw))
    }

    func test_ordinaryText_isNotSkipped() {
        let raw = RawPasteboardContent(
            types: ["public.utf8-plain-text"], string: "hello",
            imageData: nil, frontmostAppBundleId: "com.apple.Safari")
        XCTAssertFalse(SensitiveFilter().shouldSkip(raw))
    }

    func test_unknownBundleId_isNotSkipped() {
        let raw = RawPasteboardContent(
            types: ["public.utf8-plain-text"], string: "x",
            imageData: nil, frontmostAppBundleId: "com.example.unknown")
        XCTAssertFalse(SensitiveFilter().shouldSkip(raw))
    }
}
